CREATE DATABASE [bd-posfiap];

CREATE TABLE VIDEOS(
	ID BIGINT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	DESCRICAO VARCHAR(250) NOT NULL,
	SITUACAO CHAR(1) CHECK (SITUACAO IN ('P', 'S', 'E'))  NOT NULL,
	DTCAD DATETIME NOT NULL,
	DTPROC DATETIME
)
